include:
  remote: 'https://raw.githubusercontent.com/ebi-ait/gitlab-ci-templates/master/build-release-deploy.yml'

Test:
    image: quay.io/ebi-ait/ingest-base-images:python_3.10-slim
    before_script:
        - python -m venv ./venv
        - source venv/bin/activate
        - pip install --upgrade pip
    script:
        - python -m pytest tests --junitxml=report.xml
    artifacts:
        reports:
            junit:
                - report.xml
